### PR TITLE
refact(solver): remove duplicated state in form of `finish_times` array

### LINKED ISSUE #150: chore: remove duplicated state on operations finish times
## Bug description

Currently operation finish times are stored both in stack-allocated (per single individual *evaluation*) and each `Operation` holds it's finish time.
This introduces unnecessary state duplication making it harder to keep everything in sync and to decide on single source of truth.

## Expected behaviour 

There is no need for stack-allocated `finish_times` array.

### PR DESCRIPTION
**Pull request by kkafar**
## Description 

Issue described in #150. This PR removes mentioned array & replaces its usages with state stored in operation themselves. 

## Linked issues 

Closes #150

### CODE REVIEW

File: solver/src/problem/fitness.rs [hunk 1]
```diff
@@ -232,13 +225,13 @@ impl JsspFitness {
                 // space to store only the direct predecessor (list of direct predecessors?).
                 if op.id != indv.operations.len() - 1 {
                     if let Some(direct_pred_id) = op.preds.last() {
-                        if finish_times[*direct_pred_id] as f64 > time as f64 + delay {
+                        if indv.operations[*direct_pred_id].finish_time.unwrap_or(usize::MAX) as f64 > time as f64 + delay {
```
Comment (kkafar) [inline solver/src/problem/fitness.rs:228]: Previously when there was no value in `finish_times` array we would get `usize::MAX` by default. Consider keeping this behaviour or make educated decision about change.

File: solver/src/problem/fitness.rs [hunk 2]
```diff
@@ -232,13 +225,13 @@ impl JsspFitness {
...
                             return false;
                         }
                     }
                 } else {
                     for &pred in op.preds.iter() {
-                        if finish_times[pred] as f64 > time as f64 + delay {
+                        if indv.operations[pred].finish_time.unwrap_or(usize::MAX) as f64 > time as f64 + delay {
```
Comment (kkafar) [inline solver/src/problem/fitness.rs:234]: ☝🏻 same here

File: solver/src/problem/fitness.rs [hunk 3]
```diff
@@ -162,10 +156,10 @@ impl JsspFitness {
                 }
 
                 delay = self.delay_for_g(indv, n, g, maxdur);
-                j = self.update_delay_feasibles_and_highest_prior_op(indv, &finish_times, delay, t_g);
+                j = self.update_delay_feasibles_and_highest_prior_op(indv, delay, t_g);
             }
             // Update the scheduling time t_g associated with g
-            t_g = *finish_times.iter().filter(|&&t| t > t_g).min().unwrap();
+            t_g = indv.operations.iter().filter_map(|op| op.finish_time).filter(|&t| t > t_g).min().unwrap();
```
Comment (kkafar) [inline solver/src/problem/fitness.rs:162]: Keep an eye for cases where `t == usize::MAX` in old implementation.

**Review by kkafar — COMMENTED** [review]
Notes for next session.

**Comment by kkafar** [comment]
Another note: [CI is failing](https://github.com/kkafar/master-monorepo/actions/runs/8405325908/job/23017892789?pr=156) for serious reason: started to get index out of bounds error, thus current changes introduced an undesired change in behaviour. NEED TO FIND THIS!

File: solver/src/problem/fitness.rs [hunk 4]
```diff
@@ -207,7 +200,7 @@ impl JsspFitness {
 
         indv.operations
             .iter()
-            .filter(|op| finish_times[op.id] == usize::MAX)
+            .filter(|op| op.finish_time.is_some())
```
[the remark this answers is not in the document]
Comment (kkafar) [reply solver/src/problem/fitness.rs]: [7084429](https://github.com/kkafar/master-monorepo/pull/156/commits/7084429d6d066ea5155ecd2b48dc96624e3e156b)
